//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PL_MVC.ServiceReferenceProducto {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceProducto.IServiceProducto")]
    public interface IServiceProducto {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetAll", ReplyAction="http://tempuri.org/IServiceProducto/GetAllResponse")]
        System.ValueTuple<bool, string, ML.Producto[], System.Exception> GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetAll", ReplyAction="http://tempuri.org/IServiceProducto/GetAllResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string, ML.Producto[], System.Exception>> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/Add", ReplyAction="http://tempuri.org/IServiceProducto/AddResponse")]
        System.ValueTuple<bool, string, System.Exception> Add(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/Add", ReplyAction="http://tempuri.org/IServiceProducto/AddResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string, System.Exception>> AddAsync(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/Update", ReplyAction="http://tempuri.org/IServiceProducto/UpdateResponse")]
        System.ValueTuple<bool, string, System.Exception> Update(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/Update", ReplyAction="http://tempuri.org/IServiceProducto/UpdateResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string, System.Exception>> UpdateAsync(ML.Producto producto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/Delete", ReplyAction="http://tempuri.org/IServiceProducto/DeleteResponse")]
        System.ValueTuple<bool, string, ML.Producto, System.Exception> Delete(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/Delete", ReplyAction="http://tempuri.org/IServiceProducto/DeleteResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string, ML.Producto, System.Exception>> DeleteAsync(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetById", ReplyAction="http://tempuri.org/IServiceProducto/GetByIdResponse")]
        System.ValueTuple<bool, string, ML.Producto, System.Exception> GetById(int IdProducto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceProducto/GetById", ReplyAction="http://tempuri.org/IServiceProducto/GetByIdResponse")]
        System.Threading.Tasks.Task<System.ValueTuple<bool, string, ML.Producto, System.Exception>> GetByIdAsync(int IdProducto);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceProductoChannel : PL_MVC.ServiceReferenceProducto.IServiceProducto, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceProductoClient : System.ServiceModel.ClientBase<PL_MVC.ServiceReferenceProducto.IServiceProducto>, PL_MVC.ServiceReferenceProducto.IServiceProducto {
        
        public ServiceProductoClient() {
        }
        
        public ServiceProductoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceProductoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ValueTuple<bool, string, ML.Producto[], System.Exception> GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string, ML.Producto[], System.Exception>> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public System.ValueTuple<bool, string, System.Exception> Add(ML.Producto producto) {
            return base.Channel.Add(producto);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string, System.Exception>> AddAsync(ML.Producto producto) {
            return base.Channel.AddAsync(producto);
        }
        
        public System.ValueTuple<bool, string, System.Exception> Update(ML.Producto producto) {
            return base.Channel.Update(producto);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string, System.Exception>> UpdateAsync(ML.Producto producto) {
            return base.Channel.UpdateAsync(producto);
        }
        
        public System.ValueTuple<bool, string, ML.Producto, System.Exception> Delete(int IdProducto) {
            return base.Channel.Delete(IdProducto);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string, ML.Producto, System.Exception>> DeleteAsync(int IdProducto) {
            return base.Channel.DeleteAsync(IdProducto);
        }
        
        public System.ValueTuple<bool, string, ML.Producto, System.Exception> GetById(int IdProducto) {
            return base.Channel.GetById(IdProducto);
        }
        
        public System.Threading.Tasks.Task<System.ValueTuple<bool, string, ML.Producto, System.Exception>> GetByIdAsync(int IdProducto) {
            return base.Channel.GetByIdAsync(IdProducto);
        }
    }
}
